package com.CatShockEntertainment.FreePopularLiveWallpaper;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int cameras = 0x7f070000;
        public static final int visualization_style = 0x7f070001;
    }

    public static final class drawable {
        public static final int icon = 0x7f020000;
        public static final int icon2 = 0x7f020001;
        public static final int toast_icon = 0x7f020002;
    }

    public static final class id {
        public static final int colorPickerHSV_linearLayout = 0x7f080000;
        public static final int colorPickerHSV_LinearLayout_SV_H = 0x7f080001;
        public static final int colorPickerHSV_SV = 0x7f080002;
        public static final int colorPickerHSV_H = 0x7f080003;
        public static final int colorPickerHSV_HSector = 0x7f080004;
        public static final int colorPickerHSV_Preview = 0x7f080005;
        public static final int colorPickerHSV_CancelButton = 0x7f080006;
        public static final int colorPickerHSV_OkButton = 0x7f080007;
        public static final int colorPickerHSV_LinearLayout_H_HSector = 0x7f080008;
        public static final int launcher_toast_layout_root = 0x7f080009;
        public static final int launcher_toast_layout_image = 0x7f08000a;
        public static final int launcher_toast_layout_text = 0x7f08000b;
        public static final int editText_number = 0x7f08000c;
        public static final int textView_label = 0x7f08000d;
        public static final int linearLayout1 = 0x7f08000e;
        public static final int button_cancel = 0x7f08000f;
        public static final int button_ok = 0x7f080010;
        public static final int seekBar = 0x7f080011;
        public static final int preference_ad = 0x7f080012;
        public static final int textView = 0x7f080013;
        public static final int button_rate = 0x7f080014;
        public static final int button_remind = 0x7f080015;
        public static final int button_nevermind = 0x7f080016;
        public static final int seekBar_slider = 0x7f080017;
        public static final int linearLayout01 = 0x7f080018;
        public static final int ScrollView01 = 0x7f080019;
        public static final int LinearLayout02 = 0x7f08001a;
        public static final int textView1 = 0x7f08001b;
        public static final int get_full_version_button_id = 0x7f08001c;
        public static final int linearLayout03 = 0x7f08001d;
        public static final int visit_us_button_id = 0x7f08001e;
        public static final int continue_button_id = 0x7f08001f;
    }

    public static final class layout {
        public static final int color_picker_hsv_dialog = 0x7f030000;
        public static final int launcher_toast_layout = 0x7f030001;
        public static final int number_edit_dialog_layout = 0x7f030002;
        public static final int number_edit_dialog_seekbar_layout = 0x7f030003;
        public static final int preference_activity_layout = 0x7f030004;
        public static final int rate_dlg_layout = 0x7f030005;
        public static final int slider_dialog_layout = 0x7f030006;
        public static final int trial_setting_replacement_dialog_layout = 0x7f030007;
    }

    public static final class string {
        public static final int app_name = 0x7f060000;
        public static final int settings = 0x7f060001;
        public static final int get_full_version_button_caption = 0x7f060002;
        public static final int website_link_button_caption = 0x7f060003;
        public static final int unlicensed_dialog_title = 0x7f060004;
        public static final int unlicensed_dialog_body = 0x7f060005;
        public static final int buy_button = 0x7f060006;
        public static final int quit_button = 0x7f060007;
        public static final int app_name_launcher = 0x7f060008;
        public static final int other_apps_url = 0x7f060009;
        public static final int app_description = 0x7f06000a;
        public static final int trial_version_descryption = 0x7f06000b;
        public static final int get_full_version_android_market_url = 0x7f06000c;
    }

    public static final class style {
        public static final int AppBaseTheme = 0x7f050000;
        public static final int AppTheme = 0x7f050001;
    }

    public static final class xml {
        public static final int popular = 0x7f040000;
        public static final int settings = 0x7f040001;
        public static final int settings_default = 0x7f040002;
        public static final int settings_free = 0x7f040003;
    }
}
